[package]
name = "rpgn"
version = "0.3.4"
edition = "2021"
authors = ["Leonard D. <tigerros.gh@gmail.com>"]
description = "A crate for parsing PGNs (Portable [Chess] Game Notation)."
license = "GPL-3.0"
repository = "https://github.com/tigerros/rpgn"
categories = ["parser-implementations", "game-development", "parsing"]
keywords = ["chess", "pgn", "parser"]
include = ["src", "README.md"]

[dependencies]
pgn-reader = "0.26.0"
shakmaty = "0.27.2"
dry-mods = "0.1.5"
paste = "1.0.15"
fast-concat = "1.0.2"
constcat = "0.6.0"

[dev-dependencies]
test-case = "3.3.1"
pretty_assertions = "1.4.0"
proptest = "1.4.0"
criterion = "0.5.1"

[[bench]]
name = "pgn"
harness = false